GET http://localhost:3003/client/all
Content-Type: application/json

###

POST http://localhost:3003/client/create
Content-Type: application/json

{ 
  "nome": "Teste",
  "cpf": "113.123.123-12", 
  "dataNascimento":"16/10/2000"
}

###

GET http://localhost:3003/client/saldo
    ?nome=Daniel
    &cpf=123.123.123-12
Content-Type: application/json

###

PATCH http://localhost:3003/client/saldo
      ?nome=Daniel
      &cpf=123.123.123-12
      &saldo=2000
Content-Type: application/json

###

PUT http://localhost:3003/client/pagar-conta
    ?cpf=123.123.123-12
Content-Type: application/json

{
  "valor": 1000,
  "data": "02/10/2023",
  "descricao": "Investimento"
}